trigger:
  branches:
    include:
    - master
    - feature/*
  tags:
    include:
    - '*'

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: corvus-dotnet-github

jobs:
- template: templates/build.and.release.yml@recommended_practices
  parameters:
    vmImage: 'ubuntu-latest'
    service_connection_nuget_org: $(Endjin_Service_Connection_NuGet_Org)
    service_connection_github: $(Endjin_Service_Connection_GitHub)
    solution_to_build: $(Endjin_Solution_To_Build)
    postCustomEnvironmentVariables:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=CosmosDbAccountUri]$Env:ENDJIN_COSMOSDBACCOUNTURI"
          Write-Host "##vso[task.setvariable variable=CosmosDbKeySecretName]$Env:ENDJIN_COSMOSDBKEYSECRETNAME"
          Write-Host "##vso[task.setvariable variable=KeyVaultName]$Env:ENDJIN_KEYVAULTNAME"
          gci Env:
        displayName: 'Set Custom Environment Variables'
        env:
          ENDJIN_COSMOSDBACCOUNTURI: $(Endjin_CosmosDbAccountUri)
          ENDJIN_COSMOSDBKEYSECRETNAME: $(Endjin_CosmosDbKeySecretName)
          ENDJIN_KEYVAULTNAME: $(Endjin_KeyVaultName)