// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Corvus.Extensions.CosmosDb.Sql.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Store an entity in a Cosmos DB collection")]
    [NUnit.Framework.CategoryAttribute("setupContainer")]
    [NUnit.Framework.CategoryAttribute("setupCosmosDBSqlClient")]
    public partial class StoreAnEntityInACosmosDBCollectionFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "StoreAnEntityInACosmosDbCollection.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Store an entity in a Cosmos DB collection", "\tIn order to persist POCO entities\r\n\tAs a developer\r\n\tI want to be able to store " +
                    "an entity in a Cosmos DB collection", ProgrammingLanguage.CSharp, new string[] {
                        "setupContainer",
                        "setupCosmosDBSqlClient"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Store a null entity")]
        public virtual void StoreANullEntity()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Store a null entity", null, ((string[])(null)));
#line 9
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 10
 testRunner.When("I store a null entity", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("it should throw a \'System.ArgumentNullException\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 12
 testRunner.And("the ArgumentNullException applies to the parameter \'item\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Store an entity")]
        public virtual void StoreAnEntity()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Store an entity", null, ((string[])(null)));
#line 14
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table12.AddRow(new string[] {
                        "newguid",
                        "Hello",
                        "7"});
#line 15
 testRunner.When("I store an entity", ((string)(null)), table12, "When ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table13.AddRow(new string[] {
                        "newguid",
                        "Hello",
                        "7"});
#line 18
 testRunner.Then("the result should match", ((string)(null)), table13, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Insert an entity that does not exist")]
        public virtual void InsertAnEntityThatDoesNotExist()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Insert an entity that does not exist", null, ((string[])(null)));
#line 22
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table14.AddRow(new string[] {
                        "3976796e-9ff5-4ee9-aeea-ac2dceb96af6",
                        "Hello",
                        "7"});
#line 23
 testRunner.When("I insert an entity", ((string)(null)), table14, "When ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table15.AddRow(new string[] {
                        "3976796e-9ff5-4ee9-aeea-ac2dceb96af6",
                        "Hello",
                        "7"});
#line 26
 testRunner.Then("the result should match", ((string)(null)), table15, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Insert an entity that already exists")]
        public virtual void InsertAnEntityThatAlreadyExists()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Insert an entity that already exists", null, ((string[])(null)));
#line 30
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table16.AddRow(new string[] {
                        "7f3a63ad-0756-4376-9515-33ab4c3d92fc",
                        "Hello",
                        "7"});
#line 31
 testRunner.Given("I insert an entity", ((string)(null)), table16, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table17.AddRow(new string[] {
                        "7f3a63ad-0756-4376-9515-33ab4c3d92fc",
                        "World",
                        "8"});
#line 34
 testRunner.When("I insert an entity", ((string)(null)), table17, "When ");
#line 37
 testRunner.Then("it should throw a \'Microsoft.Azure.Documents.DocumentClientException, Microsoft.A" +
                    "zure.DocumentDB.Core\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 38
 testRunner.And("the DocumentClientException should have an HTTP status code of \'Conflict\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update an entity using the update method")]
        public virtual void UpdateAnEntityUsingTheUpdateMethod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update an entity using the update method", null, ((string[])(null)));
#line 40
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table18.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "First",
                        "1"});
#line 41
 testRunner.Given("I store an entity", ((string)(null)), table18, "Given ");
#line 44
 testRunner.And("I save the ETag as \'FirstVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table19.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Second",
                        "2"});
#line 45
 testRunner.And("I store an entity", ((string)(null)), table19, "And ");
#line 48
 testRunner.And("I save the ETag as \'SecondVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table20.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Third",
                        "3"});
#line 49
 testRunner.When("I update an entity with the ETag \'SecondVersion\'", ((string)(null)), table20, "When ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table21.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Third",
                        "3"});
#line 52
 testRunner.Then("the result should match", ((string)(null)), table21, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update an entity with the wrong etag using the update method")]
        public virtual void UpdateAnEntityWithTheWrongEtagUsingTheUpdateMethod()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update an entity with the wrong etag using the update method", null, ((string[])(null)));
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table22.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "First",
                        "1"});
#line 57
 testRunner.Given("I store an entity", ((string)(null)), table22, "Given ");
#line 60
 testRunner.And("I save the ETag as \'FirstVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table23.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "Second",
                        "2"});
#line 61
 testRunner.And("I store an entity", ((string)(null)), table23, "And ");
#line 64
 testRunner.And("I save the ETag as \'SecondVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table24.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "Third",
                        "3"});
#line 65
 testRunner.When("I update an entity with the ETag \'FirstVersion\'", ((string)(null)), table24, "When ");
#line 68
 testRunner.Then("it should throw a \'Microsoft.Azure.Documents.DocumentClientException, Microsoft.A" +
                    "zure.DocumentDB.Core\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 69
 testRunner.And("the DocumentClientException should have an HTTP status code of \'PreconditionFaile" +
                    "d\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update an entity with the correct etag")]
        public virtual void UpdateAnEntityWithTheCorrectEtag()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update an entity with the correct etag", null, ((string[])(null)));
#line 71
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table25.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "First",
                        "1"});
#line 72
 testRunner.Given("I store an entity", ((string)(null)), table25, "Given ");
#line 75
 testRunner.And("I save the ETag as \'FirstVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table26.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Second",
                        "2"});
#line 76
 testRunner.And("I store an entity", ((string)(null)), table26, "And ");
#line 79
 testRunner.And("I save the ETag as \'SecondVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table27.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Third",
                        "3"});
#line 80
 testRunner.When("I store an entity with the ETag \'SecondVersion\'", ((string)(null)), table27, "When ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table28.AddRow(new string[] {
                        "1f504446-e049-42dc-b005-99fbd77e79b7",
                        "Third",
                        "3"});
#line 83
 testRunner.Then("the result should match", ((string)(null)), table28, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Update an entity with the wrong etag")]
        public virtual void UpdateAnEntityWithTheWrongEtag()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Update an entity with the wrong etag", null, ((string[])(null)));
#line 87
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table29.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "First",
                        "1"});
#line 88
 testRunner.Given("I store an entity", ((string)(null)), table29, "Given ");
#line 91
 testRunner.And("I save the ETag as \'FirstVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table30.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "Second",
                        "2"});
#line 92
 testRunner.And("I store an entity", ((string)(null)), table30, "And ");
#line 95
 testRunner.And("I save the ETag as \'SecondVersion\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "Id",
                        "Name",
                        "Some value"});
            table31.AddRow(new string[] {
                        "be7883da-62ed-4680-bf49-195ba532bf98",
                        "Third",
                        "3"});
#line 96
 testRunner.When("I store an entity with the ETag \'FirstVersion\'", ((string)(null)), table31, "When ");
#line 99
 testRunner.Then("it should throw a \'Microsoft.Azure.Documents.DocumentClientException, Microsoft.A" +
                    "zure.DocumentDB.Core\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 100
 testRunner.And("the DocumentClientException should have an HTTP status code of \'PreconditionFaile" +
                    "d\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
